# User config
author: "Tohu Apps"
tagline: "Cooking apps of every flavor"
description: "Cooking apps of every flavor."
keywords: "android, mobile apps, mobile dev, mobile development, android development, software development, software engineering, software design, android dev"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
github: ""
bitbucket: "https://bitbucket.com"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed